 ## Jupyter Notebook Basics

In [26]:
a = input('Enter a string:')
if a.lower() == a.lower()[::-1]:
    print('Palindrome')
else:
    print('Not Palindrome')    


Palindrome


In [27]:
b = 30
print(b*100)

3000


#### Numpy - Numerical Python

Python Data Structures

List, Tuple, Set, Dictionary

Arrays --> Not a built in data structure in python.
Therefore, with the help of numpy, we use numpy arrays.

Properties of numpy arrays:

1. Only Homomgeneous data can be added in a numpy array
2. Fixed size
3. Size and datatype is immutable but values can change
4. Contiguous memory allocations
5. We can create n dimensional arrays using numpy




In [28]:
import numpy as np

In [29]:
lst = [43,3,2,123,4,23]
arr1 =  np.array(lst)

In [30]:
arr1.ndim
arr1[3] = 100
arr1

array([ 43,   3,   2, 100,   4,  23])

In [31]:
arr1[3:]=2
arr1

array([43,  3,  2,  2,  2,  2])

In [32]:
arr1[:] = 20
arr1

array([20, 20, 20, 20, 20, 20])

In [33]:
arr1[1:5] = 1,2,3,4
arr1

array([20,  1,  2,  3,  4, 20])

In [34]:
arr1 += 10 # broadcasting
arr1

array([30, 11, 12, 13, 14, 30])

In [35]:
arr1 > 11

array([ True, False,  True,  True,  True,  True])

In [36]:
arr1[arr1%2==0]

array([30, 12, 14, 30])

In [37]:
arr1[-1] = True
arr1[-2] = 5.5
arr1[-3] = '4'
arr1

array([30, 11, 12,  4,  5,  1])

### 2D Array

In [38]:
lst = [[4,5,6,4],
[7,8,9,66],
[4,2,3,3],
[34,2,1,55]]
arr2 = np.array(lst)
arr2.ndim # prints number of dimensions  

2

In [39]:
arr2.shape # (rows,columns)
arr2


array([[ 4,  5,  6,  4],
       [ 7,  8,  9, 66],
       [ 4,  2,  3,  3],
       [34,  2,  1, 55]])

In [40]:
arr2.size # number of elements inside array

len(arr2)

4

In [41]:
arr2.dtype

dtype('int64')

In [42]:
arr2[3,0] = -1 # to change a value in a 2D array, mention both row & column index. Here '34' changed to '-1'
arr2

array([[ 4,  5,  6,  4],
       [ 7,  8,  9, 66],
       [ 4,  2,  3,  3],
       [-1,  2,  1, 55]])

In [43]:
arr2[0::2,0]

array([4, 4])

### Advanced Indexing

In [44]:
arr2[[0,0,3],[0,3,0]]

array([ 4,  4, -1])

In [45]:
arr2[[0,2,3],[1,3,0]] = 10
arr2

array([[ 4, 10,  6,  4],
       [ 7,  8,  9, 66],
       [ 4,  2,  3, 10],
       [10,  2,  1, 55]])

In [ ]:
arr2[[0,2]] = arr2[[2,0]] # row swapping

In [47]:
arr2

array([[ 4,  2,  3, 10],
       [ 7,  8,  9, 66],
       [ 4, 10,  6,  4],
       [10,  2,  1, 55]])

In [ ]:
arr2[:,[2,3]] = arr2[:,[3,2]] # column swapping 

In [51]:
arr2

array([[ 4,  2, 10,  3],
       [ 7,  8, 66,  9],
       [ 4, 10,  4,  6],
       [10,  2, 55,  1]])

In [ ]:
arr2[arr2==10] # finding values using conditions
arr2[arr2%2==0] # even numbers

array([ 4,  2, 10,  8, 66,  4, 10,  4,  6, 10,  2])

In [ ]:
arr2[(arr2>5)&(arr2%2==0)] # Always returns 1D array

array([10,  8, 66, 10,  6, 10])